package com.michoi.db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.michoi.db.entity.RecordBean;

import com.michoi.db.dao.RecordBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recordBeanDaoConfig;

    private final RecordBeanDao recordBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recordBeanDaoConfig = daoConfigMap.get(RecordBeanDao.class).clone();
        recordBeanDaoConfig.initIdentityScope(type);

        recordBeanDao = new RecordBeanDao(recordBeanDaoConfig, this);

        registerDao(RecordBean.class, recordBeanDao);
    }
    
    public void clear() {
        recordBeanDaoConfig.getIdentityScope().clear();
    }

    public RecordBeanDao getRecordBeanDao() {
        return recordBeanDao;
    }

}
